{
  "name": "Ultimate ESPHome Sensor",
  "version": "2025.9.14",
  "home_assistant_domain": "esphome",
  "new_install_prompt_erase": false,
  "builds": [
    {
      "chipFamily": "ESP32",
      "ota": {
        "md5": "69e777e69b86cab93015d5ac2b80f3be",
        "path": "ultimate-esphome-sensor_no-bluetooth.ota.bin",
        "release_url": "https://github.com/fixtse/esp-ota",
        "summary": "Esphome version: 2025.11.5"
      }
    }    
  ]
}
