{
  "name": "Ultimate ESPHome Sensor",
  "version": "2025.12.6",
  "home_assistant_domain": "esphome",
  "new_install_prompt_erase": false,
  "builds": [
    {
      "chipFamily": "ESP32",
      "ota": {
        "md5": "b54be7f949e104fb8f0883093f6e0975",
        "path": "ultimate-esphome-sensor_no-bluetooth.ota.bin",
        "release_url": "https://github.com/fixtse/esp-ota",
        "summary": "Esphome version: 2025.12.5"
      }
    }    
  ]
}
