{
  "name": "Ultimate ESPHome Sensor",
  "version": "2025.9.9",
  "home_assistant_domain": "esphome",
  "new_install_prompt_erase": false,
  "builds": [
    {
      "chipFamily": "ESP32",
      "ota": {
        "md5": "376a5814d9446471507fd9036ee39a4c",
        "path": "ultimate-esphome-sensor_no-bluetooth.ota.bin",
        "release_url": "https://github.com/fixtse/esp-ota",
        "summary": "Esphome version: 2025.11.0"
      }
    }    
  ]
}
