{
  "name": "Ultimate ESPHome Sensor",
  "version": "2025.12.5",
  "home_assistant_domain": "esphome",
  "new_install_prompt_erase": false,
  "builds":
    [
      {
        "chipFamily": "ESP32",
        "ota":
          {
            "md5": "fce6f9078814d5e7471ab8330de4f940",
            "path": "ultimate-esphome-sensor.ota.bin",
            "release_url": "https://github.com/fixtse/esp-ota",
            "summary": "Esphome version: 2025.12.5",
          },
      },
    ],
}
