{
  "name": "Ultimate ESPHome Sensor",
  "version": "2025.9.8",
  "home_assistant_domain": "esphome",
  "new_install_prompt_erase": false,
  "builds": [
    {
      "chipFamily": "ESP32",
      "ota": {
        "md5": "9b5dbdbeb5be1e44b14fcb2beddcfe1b",
        "path": "ultimate-esphome-sensor_no-bluetooth.ota.bin",
        "release_url": "https://github.com/fixtse/esp-ota",
        "summary": "Esphome version: 2025.10.5"
      }
    }    
  ]
}
