{
  "name": "Ultimate ESPHome Sensor",
  "version": "2025.9.19",
  "home_assistant_domain": "esphome",
  "new_install_prompt_erase": false,
  "builds": [
    {
      "chipFamily": "ESP32",
      "ota": {
        "md5": "e816dd71793cd4fd5cc364f8c3e15f8c",
        "path": "ultimate-esphome-sensor_no-bluetooth.ota.bin",
        "release_url": "https://github.com/fixtse/esp-ota",
        "summary": "Esphome version: 2025.12.4"
      }
    }    
  ]
}
